### ISSUE TITLE
Which License is this code under?

### ISSUE THREAD

**Issue by MoralCode** [ivanenko/vCard#1]
I would love to potentially make use of this code as a library in a personal project of mine (that will probably be open sourced once its somewhat useful) and noticed this repository doesn't have a license and thus, I am unsure as to how I may use this code in my project.

**Comment by ivanenko** [comment]
Hi, thank you for you question, I will update license info. 
It is GNU GPL project, so feel free to use and modify it ))
If you have good ideas and changes - send me pull requests
